import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, HardHat } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Entrar | MMcosta Engenharia"},{name:"description",content:"Acesso ao sistema de gestão da MMcosta Engenharia."},{property:"og:title",content:"MMcosta Engenharia"},{property:"og:description",content:"Sistema de gestão de obras, produção e caixa."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Auth});
function Auth(){const nav=useNavigate();const [mode,setMode]=useState<"entrar"|"criar">("entrar"),[nome,setNome]=useState(""),[email,setEmail]=useState(""),[senha,setSenha]=useState(""),[erro,setErro]=useState(""),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setErro("");if(mode==="criar"){const {data,error}=await supabase.auth.signUp({email,password:senha,options:{emailRedirectTo:window.location.origin+"/auth",data:{nome}}});if(error){setErro(error.message)}else{if(data.user){await supabase.from("profiles").upsert({id:data.user.id,nome:nome||email.split("@")[0],email});if(data.session)await supabase.rpc("claim_first_admin");}setSent(true)}}else{const {data,error}=await supabase.auth.signInWithPassword({email,password:senha});if(error)setErro("E-mail ou senha incorretos.");else if(data.user){await supabase.from("profiles").upsert({id:data.user.id,nome:data.user.user_metadata.nome||email.split("@")[0],email});await supabase.rpc("claim_first_admin");nav({to:"/visao-geral"})}}setBusy(false)}
 return <main className="grid min-h-screen lg:grid-cols-[1.1fr_.9fr]"><section className="relative hidden overflow-hidden bg-foreground p-12 text-background lg:flex lg:flex-col lg:justify-between"><div><div className="font-display text-2xl font-extrabold tracking-wide">MMCOSTA</div><div className="text-[10px] font-semibold tracking-[.24em] opacity-60">FUNDAÇÕES & GEOTECNIA</div></div><div className="max-w-xl"><HardHat className="mb-8 size-12 text-primary"/><h1 className="font-display text-5xl font-bold leading-tight">Obra medida.<br/>Caixa sob controle.</h1><p className="mt-5 max-w-md text-lg opacity-65">Produção, avanço e despesas organizados por obra, sem perder o vínculo com o canteiro.</p></div><p className="font-mono text-xs opacity-40">São Paulo · Brasil</p></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-sm"><div className="mb-10 lg:hidden"><div className="font-display text-2xl font-extrabold tracking-wide">MMCOSTA</div><div className="text-[10px] font-semibold tracking-[.2em] text-muted-foreground">FUNDAÇÕES & GEOTECNIA</div></div><p className="mb-2 text-xs font-bold uppercase tracking-widest text-primary">Acesso interno</p><h2 className="font-display text-3xl font-bold">{mode==="entrar"?"Entre no sistema":"Crie seu acesso"}</h2><p className="mt-2 text-sm text-muted-foreground">Use seu e-mail profissional e sua senha.</p>{sent?<div className="mt-8 rounded-xl border border-good/30 bg-good/10 p-5 text-sm">Confira seu e-mail para confirmar o cadastro antes de entrar.</div>:<form onSubmit={submit} className="mt-8 space-y-4">{mode==="criar"&&<Input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome completo" required/>}<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" required/><Input type="password" value={senha} onChange={e=>setSenha(e.target.value)} placeholder="Senha" minLength={6} required/>{erro&&<p className="text-sm text-destructive">{erro}</p>}<Button className="w-full" disabled={busy}>{busy?"Aguarde...":mode==="entrar"?"Entrar":"Criar acesso"}<ArrowRight/></Button></form>}<button onClick={()=>{setMode(mode==="entrar"?"criar":"entrar");setSent(false)}} className="mt-6 text-sm text-primary hover:underline">{mode==="entrar"?"Primeiro acesso? Criar conta":"Já possui acesso? Entrar"}</button></div></section></main>}
