import { Link, useLocation, useNavigate } from "@tanstack/react-router";
import { Banknote, Building2, ClipboardList, FileSpreadsheet, FileText, LayoutDashboard, Moon, ReceiptText, Settings2, Sun, Users } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { dateBR } from "@/lib/erp";
import logoAsset from "@/assets/mmcosta-logo.png.asset.json";

const nav=[
  ["Visão geral", "/visao-geral", LayoutDashboard], ["Obras", "/obras", Building2], ["Financeiro", "/financeiro", Banknote], ["Comprovantes", "/comprovantes", ReceiptText], ["Funcionários", "/funcionarios", Users], ["Cadastros", "/cadastros", Settings2],
] as const;
const workNav=[
  ["Painel da obra", "painel", Building2], ["Boletim", "boletim", ClipboardList], ["Medições", "medicoes", FileSpreadsheet], ["Documentos", "documentos", FileText],
] as const;
export function AppShell({children}:{children:ReactNode}){
 const location=useLocation(),navigate=useNavigate(),qc=useQueryClient(); const [dark,setDark]=useState(false); const match=location.pathname.match(/^\/obras\/([^/]+)/); const activeId=match?.[1];
 const {data:access}=useQuery({queryKey:["shell-role"],queryFn:async()=>{const {data:user}=await supabase.auth.getUser();if(!user.user)return{admin:false,canManage:false,canFinance:false};const [{data:admin},{data:canManage},{data:rh}]=await Promise.all([supabase.rpc("has_role",{_user_id:user.user.id,_role:"admin"}),supabase.rpc("can_manage"),supabase.rpc("has_role",{_user_id:user.user.id,_role:"engenharia"})]);return{admin:Boolean(admin),canManage:Boolean(canManage),canFinance:Boolean(canManage)||Boolean(rh)}}});
 const {data:currentWork}=useQuery({queryKey:["shell-obra",activeId],enabled:Boolean(activeId),queryFn:async()=>{const {data}=await supabase.from("obras").select("nome,clientes(nome)").eq("id",activeId!).maybeSingle();return data}});
 useEffect(()=>{const saved=localStorage.getItem("theme");const useDark=saved? saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;setDark(useDark);document.documentElement.classList.toggle("dark",useDark)},[]);
 const toggle=()=>{const n=!dark;setDark(n);document.documentElement.classList.toggle("dark",n);localStorage.setItem("theme",n?"dark":"light")};
 const logout=async()=>{await qc.cancelQueries();qc.clear();await supabase.auth.signOut();navigate({to:"/auth",replace:true})};
 return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-[1600px] items-center gap-5 px-4 py-3 lg:px-8"><Link to="/visao-geral" className="shrink-0" aria-label="Voltar à Visão geral"><img src={logoAsset.url} alt="MMcosta Engenharia" className="h-14 w-auto dark:brightness-0 dark:invert"/></Link>{activeId&&<div className="flex min-w-0 items-center gap-2 overflow-hidden rounded-full bg-primary/10 px-3 py-1.5"><Building2 className="size-4 shrink-0 text-primary"/><span className="min-w-0"><span className="block truncate text-sm font-bold leading-tight text-primary">{currentWork?.nome??"Carregando obra…"}</span>{currentWork?.clientes?.nome&&<span className="block truncate text-[10px] leading-tight text-muted-foreground">{currentWork.clientes.nome}</span>}</span></div>}<div className="ml-auto hidden font-mono text-xs text-muted-foreground md:block">{dateBR(new Date())}</div><Button variant="ghost" size="icon" onClick={toggle} aria-label="Alternar tema">{dark?<Sun/>:<Moon/>}</Button><Button variant="ghost" size="sm" onClick={logout}>Sair</Button></div><nav className="mx-auto flex max-w-[1600px] gap-1 overflow-x-auto px-4 pb-2 lg:px-8">{nav.map(([label,target,Icon])=>{if(target==="/financeiro"&&!access?.canFinance)return null;const active=target==="/obras"?location.pathname==="/obras"||location.pathname.startsWith("/obras/"):location.pathname===target;const cls=`flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2 text-xs font-semibold ${active?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`;return <Link key={label} to={target} className={cls}><Icon className="size-4"/>{label}</Link>})}</nav>{activeId&&<nav className="mx-auto flex max-w-[1600px] gap-1 overflow-x-auto border-t bg-muted/40 px-4 lg:px-8"><span className="shrink-0 self-center pr-1 text-[10px] font-bold uppercase text-muted-foreground">Nesta obra</span>{workNav.map(([label,target,Icon])=>{const active=location.pathname.endsWith(`/${target}`);const cls=`flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2 text-xs font-semibold ${active?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`;if(target==="painel")return <Link key={label} to="/obras/$id/painel" params={{id:activeId}} className={cls}><Icon className="size-4"/>{label}</Link>;return <Link key={label} to="/obras/$id/$secao" params={{id:activeId,secao:target}} className={cls}><Icon className="size-4"/>{label}</Link>})}</nav>}</header><main className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8">{children}</main></div>
}
