import { Link, useLocation, useNavigate } from "@tanstack/react-router";
import { Building2, ClipboardList, FileSpreadsheet, FileText, LayoutDashboard, Moon, ReceiptText, Settings2, Sun, WalletCards } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { dateBR } from "@/lib/erp";

const nav=[
  ["Visão geral", "/visao-geral", LayoutDashboard], ["Painel da obra", "painel", Building2], ["Boletim", "boletim", ClipboardList], ["Medições", "medicoes", FileSpreadsheet], ["Importar medição", "importar", FileSpreadsheet], ["Comprovantes", "comprovantes", ReceiptText], ["Documentos", "documentos", FileText], ["Cadastros", "/cadastros", Settings2],
] as const;
export function AppShell({children}:{children:ReactNode}){
 const location=useLocation(),navigate=useNavigate(),qc=useQueryClient(); const [dark,setDark]=useState(false); const match=location.pathname.match(/^\/obras\/([^/]+)/); const activeId=match?.[1];
 const {data:obras=[]}=useQuery({queryKey:["obras-nav"],queryFn:async()=>{const {data,error}=await supabase.from("obras").select("id,nome,status,ativo").eq("ativo",true).order("data_inicio");if(error)throw error;return data;}});
 useEffect(()=>{const saved=localStorage.getItem("theme");const useDark=saved? saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;setDark(useDark);document.documentElement.classList.toggle("dark",useDark)},[]);
 const toggle=()=>{const n=!dark;setDark(n);document.documentElement.classList.toggle("dark",n);localStorage.setItem("theme",n?"dark":"light")};
 const logout=async()=>{await qc.cancelQueries();qc.clear();await supabase.auth.signOut();navigate({to:"/auth",replace:true})};
 return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-[1600px] items-center gap-5 px-4 py-3 lg:px-8"><Link to="/visao-geral" className="shrink-0"><div className="font-display text-xl font-extrabold tracking-wide">MMCOSTA</div><div className="text-[9px] font-semibold tracking-[.18em] text-muted-foreground">FUNDAÇÕES & GEOTECNIA</div></Link><div className="hidden flex-1 items-center gap-2 overflow-x-auto lg:flex">{obras.map(o=><Link key={o.id} to="/obras/$id/painel" params={{id:o.id}} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-medium ${activeId===o.id?"border-primary bg-primary text-primary-foreground":"border-border bg-card hover:border-primary/50"}`}>{o.nome.replace("PM Osasco — ","").replace("Kablan — ","")}</Link>)}<Link to="/cadastros" className="shrink-0 rounded-full border border-dashed border-primary px-3 py-1.5 text-xs font-semibold text-primary">+ Nova obra</Link></div><div className="ml-auto hidden font-mono text-xs text-muted-foreground md:block">{dateBR(new Date())}</div><Button variant="ghost" size="icon" onClick={toggle} aria-label="Alternar tema">{dark?<Sun/>:<Moon/>}</Button><Button variant="ghost" size="sm" onClick={logout}>Sair</Button></div><nav className="mx-auto flex max-w-[1600px] gap-1 overflow-x-auto px-4 pb-2 lg:px-8">{nav.map(([label,target,Icon])=>{const active=target.startsWith("/")?location.pathname===target:location.pathname.endsWith(`/${target}`);const cls=`flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2 text-xs font-semibold ${active?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`;if(target==="/visao-geral")return <Link key={label} to="/visao-geral" className={cls}><Icon className="size-4"/>{label}</Link>;if(target==="/cadastros")return <Link key={label} to="/cadastros" className={cls}><Icon className="size-4"/>{label}</Link>;if(!activeId)return <Link key={label} to="/visao-geral" className={cls}><Icon className="size-4"/>{label}</Link>;if(target==="painel")return <Link key={label} to="/obras/$id/painel" params={{id:activeId}} className={cls}><Icon className="size-4"/>{label}</Link>;return <Link key={label} to="/obras/$id/$secao" params={{id:activeId,secao:target}} className={cls}><Icon className="size-4"/>{label}</Link>})}</nav></header><main className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8">{children}</main></div>
}
