import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Building2, CalendarDays, HardHat, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { daysBetween, obraHealth, pct } from "@/lib/erp";
export const Route=createFileRoute("/_authenticated/visao-geral")({head:()=>({meta:[{title:"Visão geral | MMcosta Engenharia"},{name:"description",content:"Obras em execução, equipes e equipamentos em operação da MMcosta Engenharia."},{property:"og:title",content:"Visão geral | MMcosta Engenharia"},{property:"og:description",content:"Resumo financeiro e físico das obras ativas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Overview});
function Overview(){const {data,isLoading,error}=useQuery({queryKey:["overview"],queryFn:async()=>{const [{data:obras,error:o},{data:marcos,error:m},{data:clientes,error:c},{data:funcionarios,error:f},{data:aloc,error:a},{data:equip,error:e}]=await Promise.all([supabase.from("obras").select("*").eq("ativo",true).order("data_inicio"),supabase.from("marcos_avanco").select("*").order("data"),supabase.from("clientes").select("id,nome"),supabase.from("funcionarios").select("id,ativo").eq("ativo",true),supabase.from("funcionario_alocacoes").select("funcionario_id,obra_id,data_inicio,data_fim"),supabase.from("obra_equipamentos").select("obra_id,data_entrada,data_saida,equipamentos(id,codigo,descricao,tipo,ativo)")]);if(o||m||c||f||a||e)throw(o||m||c||f||a||e);return{obras:obras??[],marcos:marcos??[],clientes:clientes??[],funcionarios:funcionarios??[],aloc:aloc??[],equip:equip??[]}}});if(isLoading)return <p className="text-sm text-muted-foreground">Carregando visão geral...</p>;if(error||!data)return <p className="text-sm text-destructive">Não foi possível carregar a visão geral.</p>;
 const day=new Date().toISOString().slice(0,10),running=data.obras.filter(o=>o.status==="em_andamento"),runningIds=new Set(running.map(o=>o.id));
 const activeStaff=new Set(data.funcionarios.map(x=>x.id)),staffByWork=new Map<string,Set<string>>();for(const a of data.aloc){if(!a.obra_id||!runningIds.has(a.obra_id)||!activeStaff.has(a.funcionario_id)||a.data_inicio>day||(a.data_fim&&a.data_fim<day))continue;(staffByWork.get(a.obra_id)??staffByWork.set(a.obra_id,new Set()).get(a.obra_id)!).add(a.funcionario_id)}
 const isRig=(e:{descricao:string;tipo:string|null}|null)=>Boolean(e)&&/perfuratriz/i.test(`${e!.descricao} ${e!.tipo??""}`),rigsByWork=new Map<string,Set<string>>();for(const r of data.equip){const e=r.equipamentos;if(!e||!e.ativo||!isRig(e)||!runningIds.has(r.obra_id)||(r.data_entrada&&r.data_entrada>day)||(r.data_saida&&r.data_saida<day))continue;(rigsByWork.get(r.obra_id)??rigsByWork.set(r.obra_id,new Set()).get(r.obra_id)!).add(e.id)}
 const staffTotal=new Set([...staffByWork.values()].flatMap(s=>[...s])).size,rigTotal=new Set([...rigsByWork.values()].flatMap(s=>[...s])).size;
 const summaries=running.map(o=>{const last=data.marcos.filter(x=>x.obra_id===o.id).at(-1),physical=last?.percentual_fisico??0,elapsed=Math.min(100,daysBetween(o.data_inicio,day)/daysBetween(o.data_inicio,o.data_fim_prevista)*100);return{o,physical,elapsed,staff:staffByWork.get(o.id)?.size??0,rigs:rigsByWork.get(o.id)?.size??0,health:obraHealth(o.status,o.data_inicio,o.data_fim_prevista,physical)}});
 return <><header className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Empresa</p><h1 className="font-display text-3xl font-bold">Visão geral</h1><p className="mt-1 text-sm text-muted-foreground">Operação atual das obras em execução.</p></div></header><section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3">{([["Obras em execução",running.length,"em andamento hoje",<Building2 className="size-4"/>],["Funcionários em operação",staffTotal,`${Math.max(0,data.funcionarios.length-staffTotal)} no depósito/administrativo`,<Users className="size-4"/>],["Perfuratrizes em operação",rigTotal,"alocadas em obras em execução",<HardHat className="size-4"/>]] as const).map(([l,v,s,icon])=><div key={l} className="bg-card p-5"><p className="flex items-center gap-2 text-xs font-semibold uppercase text-muted-foreground">{icon}{l}</p><p className="mt-2 font-mono text-3xl font-semibold">{v}</p><p className="mt-1 text-xs text-muted-foreground">{s}</p></div>)}</section><div className="mt-8 grid gap-5 xl:grid-cols-2">{summaries.map(s=><Link key={s.o.id} to="/obras/$id/painel" params={{id:s.o.id}} className="group border-t-4 border-primary bg-card p-6 shadow-sm ring-1 ring-border transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium text-muted-foreground">{data.clientes.find(c=>c.id===s.o.cliente_id)?.nome}</p><h2 className="mt-1 font-display text-xl font-bold">{s.o.nome}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${s.health.tone==="good"?"bg-good/10 text-good":s.health.tone==="warn"?"bg-warning/15 text-warning":"bg-destructive/10 text-destructive"}`}>{s.health.label}</span></div><div className="mt-6 grid grid-cols-2 gap-4 border-y py-4"><Mini label="Funcionários na obra" value={String(s.staff)}/><Mini label="Perfuratrizes na obra" value={String(s.rigs)}/></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Progress icon={<CalendarDays/>} label="Prazo decorrido" value={s.elapsed}/><Progress icon={<Building2/>} label="Avanço físico" value={s.physical}/></div><div className="mt-5 flex justify-end text-xs font-bold text-primary">Abrir painel <ArrowUpRight className="ml-1 size-4"/></div></Link>)}{summaries.length===0&&<p className="col-span-full py-10 text-center text-sm text-muted-foreground">Nenhuma obra em execução no momento.</p>}</div></>}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div>}
function Progress({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="flex items-center gap-1.5 text-muted-foreground [&_svg]:size-3.5">{icon}{label}</span><span className="font-mono font-semibold">{pct(value)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,value)}%`}}/></div></div>}
