import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Building2, CalendarDays } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { brl, daysBetween, obraHealth, pct } from "@/lib/erp";
export const Route=createFileRoute("/_authenticated/visao-geral")({head:()=>({meta:[{title:"Visão geral | MMcosta Engenharia"},{name:"description",content:"Resumo financeiro e físico das obras ativas da MMcosta Engenharia."},{property:"og:title",content:"Visão geral | MMcosta Engenharia"},{property:"og:description",content:"Resumo financeiro e físico das obras ativas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Overview});
function Overview(){const {data,isLoading,isError}=useQuery({queryKey:["overview","v2"],queryFn:async()=>{const [{data:obras,error:o},{data:lanc,error:l},{data:marcos,error:m},{data:clientes,error:c}]=await Promise.all([supabase.from("obras").select("*").eq("ativo",true).order("data_inicio"),supabase.from("lancamentos").select("obra_id,tipo,valor,categoria").is("deleted_at",null),supabase.from("marcos_avanco").select("*").order("data"),supabase.from("clientes").select("id,nome")]);if(o||l||m||c)throw(o||l||m||c);return{obras:obras??[],lanc:lanc??[],marcos:marcos??[],clientes:clientes??[]}}});if(isLoading)return <p className="text-sm text-muted-foreground">Carregando visão geral...</p>;if(isError)return <p className="text-sm text-destructive">Não foi possível carregar a visão geral. Tente novamente.</p>;
 const obras=data?.obras??[],lanc=data?.lanc??[],marcos=data?.marcos??[],clientes=data?.clientes??[];const summaries=obras.map(o=>{const ls=lanc.filter(x=>x.obra_id===o.id),received=ls.filter(x=>x.tipo==="recebimento").reduce((s,x)=>s+x.valor,0),paid=ls.filter(x=>x.tipo==="pagamento").reduce((s,x)=>s+x.valor,0),last=marcos.filter(x=>x.obra_id===o.id).at(-1),physical=last?.percentual_fisico??0,elapsed=Math.min(100,daysBetween(o.data_inicio,new Date().toISOString().slice(0,10))/daysBetween(o.data_inicio,o.data_fim_prevista)*100);return{o,received,paid,physical,elapsed,health:obraHealth(o.status,o.data_inicio,o.data_fim_prevista,physical)}});const total=summaries.reduce((a,s)=>({contracts:a.contracts+s.o.valor_contrato,received:a.received+s.received,paid:a.paid+s.paid}),{contracts:0,received:0,paid:0});return <><header className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Empresa</p><h1 className="font-display text-3xl font-bold">Visão geral</h1><p className="mt-1 text-sm text-muted-foreground">Desempenho consolidado das obras ativas.</p></div></header><section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-2 lg:grid-cols-4">{[["Contratos ativos",total.contracts],["Recebido",total.received],["Pago",total.paid],["Saldo consolidado",total.received-total.paid]].map(([l,v])=><div key={String(l)} className="bg-card p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">{l}</p><p className="mt-2 font-mono text-2xl font-semibold">{brl.format(Number(v))}</p></div>)}</section><div className="mt-8 grid gap-5 xl:grid-cols-2">{summaries.map(s=><Link key={s.o.id} to="/obras/$id/painel" params={{id:s.o.id}} className="group border-t-4 border-primary bg-card p-6 shadow-sm ring-1 ring-border transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium text-muted-foreground">{clientes.find(c=>c.id===s.o.cliente_id)?.nome}</p><h2 className="mt-1 font-display text-xl font-bold">{s.o.nome}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${s.health.tone==="good"?"bg-good/10 text-good":s.health.tone==="warn"?"bg-warning/15 text-warning":"bg-destructive/10 text-destructive"}`}>{s.health.label}</span></div><div className="mt-6 grid grid-cols-3 gap-4 border-y py-4"><Mini label="Recebido" value={brl.format(s.received)}/><Mini label="Pago" value={brl.format(s.paid)}/><Mini label="Saldo" value={brl.format(s.received-s.paid)}/></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Progress icon={<CalendarDays/>} label="Prazo decorrido" value={s.elapsed}/><Progress icon={<Building2/>} label="Avanço físico" value={s.physical}/></div><div className="mt-5 flex justify-end text-xs font-bold text-primary">Abrir painel <ArrowUpRight className="ml-1 size-4"/></div></Link>)}</div></>}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div>}
function Progress({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="flex items-center gap-1.5 text-muted-foreground [&_svg]:size-3.5">{icon}{label}</span><span className="font-mono font-semibold">{pct(value)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,value)}%`}}/></div></div>}
