/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as ApiLerBoletimRouteImport } from './routes/api/ler-boletim'
import { Route as ApiLerComprovantesRouteImport } from './routes/api/ler-comprovantes'
import { Route as AuthenticatedObrasIdSecaoRouteImport } from './routes/_authenticated/obras/$id/$secao'
import { Route as AuthenticatedObrasIdPainelRouteImport } from './routes/_authenticated/obras/$id/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLerBoletimRoute = ApiLerBoletimRouteImport.update({
  id: '/api/ler-boletim',
  path: '/api/ler-boletim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLerComprovantesRoute = ApiLerComprovantesRouteImport.update({
  id: '/api/ler-comprovantes',
  path: '/api/ler-comprovantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasIdSecaoRoute =
  AuthenticatedObrasIdSecaoRouteImport.update({
    id: '/obras/$id/$secao',
    path: '/obras/$id/$secao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObrasIdPainelRoute =
  AuthenticatedObrasIdPainelRouteImport.update({
    id: '/obras/$id/painel',
    path: '/obras/$id/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/ler-boletim': typeof ApiLerBoletimRoute
  '/api/ler-comprovantes': typeof ApiLerComprovantesRoute
  '/obras/$id/$secao': typeof AuthenticatedObrasIdSecaoRoute
  '/obras/$id/painel': typeof AuthenticatedObrasIdPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/ler-boletim': typeof ApiLerBoletimRoute
  '/api/ler-comprovantes': typeof ApiLerComprovantesRoute
  '/obras/$id/$secao': typeof AuthenticatedObrasIdSecaoRoute
  '/obras/$id/painel': typeof AuthenticatedObrasIdPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/ler-boletim': typeof ApiLerBoletimRoute
  '/api/ler-comprovantes': typeof ApiLerComprovantesRoute
  '/_authenticated/obras/$id/$secao': typeof AuthenticatedObrasIdSecaoRoute
  '/_authenticated/obras/$id/painel': typeof AuthenticatedObrasIdPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastros'
    | '/visao-geral'
    | '/api/ler-boletim'
    | '/api/ler-comprovantes'
    | '/obras/$id/$secao'
    | '/obras/$id/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastros'
    | '/visao-geral'
    | '/api/ler-boletim'
    | '/api/ler-comprovantes'
    | '/obras/$id/$secao'
    | '/obras/$id/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cadastros'
    | '/_authenticated/visao-geral'
    | '/api/ler-boletim'
    | '/api/ler-comprovantes'
    | '/_authenticated/obras/$id/$secao'
    | '/_authenticated/obras/$id/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiLerBoletimRoute: typeof ApiLerBoletimRoute
  ApiLerComprovantesRoute: typeof ApiLerComprovantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ler-boletim': {
      id: '/api/ler-boletim'
      path: '/api/ler-boletim'
      fullPath: '/api/ler-boletim'
      preLoaderRoute: typeof ApiLerBoletimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ler-comprovantes': {
      id: '/api/ler-comprovantes'
      path: '/api/ler-comprovantes'
      fullPath: '/api/ler-comprovantes'
      preLoaderRoute: typeof ApiLerComprovantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/$id/$secao': {
      id: '/_authenticated/obras/$id/$secao'
      path: '/obras/$id/$secao'
      fullPath: '/obras/$id/$secao'
      preLoaderRoute: typeof AuthenticatedObrasIdSecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$id/painel': {
      id: '/_authenticated/obras/$id/painel'
      path: '/obras/$id/painel'
      fullPath: '/obras/$id/painel'
      preLoaderRoute: typeof AuthenticatedObrasIdPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedObrasIdSecaoRoute: typeof AuthenticatedObrasIdSecaoRoute
  AuthenticatedObrasIdPainelRoute: typeof AuthenticatedObrasIdPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedObrasIdSecaoRoute: AuthenticatedObrasIdSecaoRoute,
  AuthenticatedObrasIdPainelRoute: AuthenticatedObrasIdPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiLerBoletimRoute: ApiLerBoletimRoute,
  ApiLerComprovantesRoute: ApiLerComprovantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
