REVOKE ALL ON FUNCTION public.has_role(uuid,public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
REVOKE ALL ON FUNCTION public.can_manage() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_manage() TO authenticated;
REVOKE ALL ON FUNCTION public.can_field() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_field() TO authenticated;
REVOKE ALL ON FUNCTION public.claim_first_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_first_admin() TO authenticated;
REVOKE ALL ON FUNCTION public.create_obra_cost_center() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_lancamentos() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;