CREATE TYPE public.app_role AS ENUM ('admin','escritorio','engenharia','leitura');
CREATE TYPE public.obra_status AS ENUM ('em_andamento','concluida','suspensa');
CREATE TYPE public.centro_custo_tipo AS ENUM ('obra','administrativo');
CREATE TYPE public.lancamento_tipo AS ENUM ('recebimento','pagamento');

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;

CREATE TABLE public.profiles(id uuid PRIMARY KEY,nome text NOT NULL,email text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.user_roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,role public.app_role NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,UNIQUE(user_id,role));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE OR REPLACE FUNCTION public.can_manage() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'escritorio') $$;
CREATE OR REPLACE FUNCTION public.can_field() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.can_manage() OR public.has_role(auth.uid(),'engenharia') $$;
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated USING(true);
CREATE POLICY profiles_insert_self ON public.profiles FOR INSERT TO authenticated WITH CHECK(id=auth.uid());
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid() OR public.has_role(auth.uid(),'admin')) WITH CHECK(id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY roles_read ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY roles_admin_insert ON public.user_roles FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE POLICY roles_admin_update ON public.user_roles FOR UPDATE TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE POLICY roles_admin_delete ON public.user_roles FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE OR REPLACE FUNCTION public.claim_first_admin() RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF; IF EXISTS(SELECT 1 FROM public.user_roles) THEN RETURN false; END IF; INSERT INTO public.user_roles(user_id,role,created_by) VALUES(auth.uid(),'admin',auth.uid()) ON CONFLICT DO NOTHING; RETURN true; END $$;
GRANT EXECUTE ON FUNCTION public.claim_first_admin() TO authenticated;

CREATE TABLE public.clientes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nome text NOT NULL,cnpj text,contato text,observacoes text,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.clientes TO authenticated; GRANT ALL ON public.clientes TO service_role; ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY clientes_read ON public.clientes FOR SELECT TO authenticated USING(true); CREATE POLICY clientes_insert ON public.clientes FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY clientes_update ON public.clientes FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY clientes_delete ON public.clientes FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.obras(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nome text NOT NULL,cliente_id uuid NOT NULL REFERENCES public.clientes(id),tipo_obra text NOT NULL,numero_contrato text,valor_contrato numeric(14,2) NOT NULL DEFAULT 0,data_inicio date NOT NULL,data_fim_prevista date NOT NULL,status public.obra_status NOT NULL DEFAULT 'em_andamento',observacoes text,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.obras TO authenticated; GRANT ALL ON public.obras TO service_role; ALTER TABLE public.obras ENABLE ROW LEVEL SECURITY;
CREATE POLICY obras_read ON public.obras FOR SELECT TO authenticated USING(true); CREATE POLICY obras_insert ON public.obras FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY obras_update ON public.obras FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY obras_delete ON public.obras FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.centros_custo(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nome text NOT NULL,tipo public.centro_custo_tipo NOT NULL,obra_id uuid UNIQUE REFERENCES public.obras(id),ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,CHECK((tipo='obra' AND obra_id IS NOT NULL) OR (tipo='administrativo' AND obra_id IS NULL)));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.centros_custo TO authenticated; GRANT ALL ON public.centros_custo TO service_role; ALTER TABLE public.centros_custo ENABLE ROW LEVEL SECURITY;
CREATE POLICY cc_read ON public.centros_custo FOR SELECT TO authenticated USING(true); CREATE POLICY cc_insert ON public.centros_custo FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY cc_update ON public.centros_custo FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY cc_delete ON public.centros_custo FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE OR REPLACE FUNCTION public.create_obra_cost_center() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.centros_custo(nome,tipo,obra_id,created_by) VALUES(NEW.nome,'obra',NEW.id,NEW.created_by); RETURN NEW; END $$;
CREATE TRIGGER create_obra_cc AFTER INSERT ON public.obras FOR EACH ROW EXECUTE FUNCTION public.create_obra_cost_center();

CREATE TABLE public.cc_aliases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),centro_custo_id uuid NOT NULL REFERENCES public.centros_custo(id) ON DELETE CASCADE,texto_normalizado text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cc_aliases TO authenticated; GRANT ALL ON public.cc_aliases TO service_role; ALTER TABLE public.cc_aliases ENABLE ROW LEVEL SECURITY;
CREATE POLICY alias_read ON public.cc_aliases FOR SELECT TO authenticated USING(true); CREATE POLICY alias_insert ON public.cc_aliases FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY alias_update ON public.cc_aliases FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY alias_delete ON public.cc_aliases FOR DELETE TO authenticated USING(public.can_manage());

CREATE TABLE public.equipamentos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),codigo text NOT NULL UNIQUE,descricao text NOT NULL,tipo text,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.equipamentos TO authenticated; GRANT ALL ON public.equipamentos TO service_role; ALTER TABLE public.equipamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY equipamentos_read ON public.equipamentos FOR SELECT TO authenticated USING(true); CREATE POLICY equipamentos_insert ON public.equipamentos FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY equipamentos_update ON public.equipamentos FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY equipamentos_delete ON public.equipamentos FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.obra_equipamentos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),obra_id uuid NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,equipamento_id uuid NOT NULL REFERENCES public.equipamentos(id),data_entrada date,data_saida date,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,UNIQUE(obra_id,equipamento_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.obra_equipamentos TO authenticated; GRANT ALL ON public.obra_equipamentos TO service_role; ALTER TABLE public.obra_equipamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY oe_read ON public.obra_equipamentos FOR SELECT TO authenticated USING(true); CREATE POLICY oe_insert ON public.obra_equipamentos FOR INSERT TO authenticated WITH CHECK(public.can_field()); CREATE POLICY oe_update ON public.obra_equipamentos FOR UPDATE TO authenticated USING(public.can_field()) WITH CHECK(public.can_field()); CREATE POLICY oe_delete ON public.obra_equipamentos FOR DELETE TO authenticated USING(public.can_manage());

CREATE TABLE public.equipes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nome text NOT NULL UNIQUE,ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.equipes TO authenticated; GRANT ALL ON public.equipes TO service_role; ALTER TABLE public.equipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY equipes_read ON public.equipes FOR SELECT TO authenticated USING(true); CREATE POLICY equipes_insert ON public.equipes FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY equipes_update ON public.equipes FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY equipes_delete ON public.equipes FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.obra_equipes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),obra_id uuid NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,equipe_id uuid NOT NULL REFERENCES public.equipes(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,UNIQUE(obra_id,equipe_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.obra_equipes TO authenticated; GRANT ALL ON public.obra_equipes TO service_role; ALTER TABLE public.obra_equipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY oeq_read ON public.obra_equipes FOR SELECT TO authenticated USING(true); CREATE POLICY oeq_insert ON public.obra_equipes FOR INSERT TO authenticated WITH CHECK(public.can_field()); CREATE POLICY oeq_update ON public.obra_equipes FOR UPDATE TO authenticated USING(public.can_field()) WITH CHECK(public.can_field()); CREATE POLICY oeq_delete ON public.obra_equipes FOR DELETE TO authenticated USING(public.can_manage());

CREATE TABLE public.categorias_lancamento(id text PRIMARY KEY,nome text NOT NULL,tipo_permitido text NOT NULL CHECK(tipo_permitido IN('recebimento','pagamento','ambos')),ativo boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.categorias_lancamento TO authenticated; GRANT ALL ON public.categorias_lancamento TO service_role; ALTER TABLE public.categorias_lancamento ENABLE ROW LEVEL SECURITY;
CREATE POLICY cat_read ON public.categorias_lancamento FOR SELECT TO authenticated USING(true); CREATE POLICY cat_insert ON public.categorias_lancamento FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(),'admin')); CREATE POLICY cat_update ON public.categorias_lancamento FOR UPDATE TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin')); CREATE POLICY cat_delete ON public.categorias_lancamento FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.lancamentos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),centro_custo_id uuid NOT NULL REFERENCES public.centros_custo(id),obra_id uuid REFERENCES public.obras(id),data date NOT NULL,tipo public.lancamento_tipo NOT NULL,categoria text NOT NULL REFERENCES public.categorias_lancamento(id),descricao text NOT NULL,valor numeric(14,2) NOT NULL CHECK(valor>0),medicao_id uuid,importacao_id uuid,comprovante_numero text,funcionario text,anexo_path text,deleted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.lancamentos TO authenticated; GRANT ALL ON public.lancamentos TO service_role; ALTER TABLE public.lancamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY lancamentos_read ON public.lancamentos FOR SELECT TO authenticated USING(public.can_manage() OR public.has_role(auth.uid(),'leitura')); CREATE POLICY lancamentos_insert ON public.lancamentos FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY lancamentos_update ON public.lancamentos FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY lancamentos_delete ON public.lancamentos FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));

CREATE TABLE public.curva_planejada(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),obra_id uuid NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,data date NOT NULL,percentual_fisico_planejado numeric(6,3) NOT NULL,percentual_financeiro_planejado numeric(6,3) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,UNIQUE(obra_id,data));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.curva_planejada TO authenticated; GRANT ALL ON public.curva_planejada TO service_role; ALTER TABLE public.curva_planejada ENABLE ROW LEVEL SECURITY;
CREATE POLICY curva_read ON public.curva_planejada FOR SELECT TO authenticated USING(true); CREATE POLICY curva_insert ON public.curva_planejada FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY curva_update ON public.curva_planejada FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY curva_delete ON public.curva_planejada FOR DELETE TO authenticated USING(public.can_manage());

CREATE TABLE public.marcos_avanco(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),obra_id uuid NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,data date NOT NULL,percentual_fisico numeric(6,3) NOT NULL,percentual_financeiro numeric(6,3) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),created_by uuid,UNIQUE(obra_id,data));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.marcos_avanco TO authenticated; GRANT ALL ON public.marcos_avanco TO service_role; ALTER TABLE public.marcos_avanco ENABLE ROW LEVEL SECURITY;
CREATE POLICY marcos_read ON public.marcos_avanco FOR SELECT TO authenticated USING(true); CREATE POLICY marcos_insert ON public.marcos_avanco FOR INSERT TO authenticated WITH CHECK(public.can_manage()); CREATE POLICY marcos_update ON public.marcos_avanco FOR UPDATE TO authenticated USING(public.can_manage()) WITH CHECK(public.can_manage()); CREATE POLICY marcos_delete ON public.marcos_avanco FOR DELETE TO authenticated USING(public.can_manage());

CREATE TABLE public.audit_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,tabela text NOT NULL,registro_id uuid NOT NULL,acao text NOT NULL,dados_antes jsonb,dados_depois jsonb,criado_em timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.audit_log TO authenticated; GRANT ALL ON public.audit_log TO service_role; ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_read ON public.audit_log FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE OR REPLACE FUNCTION public.audit_lancamentos() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.audit_log(user_id,tabela,registro_id,acao,dados_antes,dados_depois) VALUES(auth.uid(),'lancamentos',COALESCE(NEW.id,OLD.id),TG_OP,CASE WHEN TG_OP IN('UPDATE','DELETE') THEN to_jsonb(OLD) END,CASE WHEN TG_OP IN('INSERT','UPDATE') THEN to_jsonb(NEW) END); RETURN COALESCE(NEW,OLD); END $$;
CREATE TRIGGER audit_lancamentos AFTER INSERT OR UPDATE OR DELETE ON public.lancamentos FOR EACH ROW EXECUTE FUNCTION public.audit_lancamentos();

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['profiles','user_roles','clientes','obras','centros_custo','cc_aliases','equipamentos','obra_equipamentos','equipes','obra_equipes','categorias_lancamento','lancamentos','curva_planejada','marcos_avanco'] LOOP EXECUTE format('CREATE TRIGGER set_%I_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()',t,t); END LOOP; END $$;
CREATE INDEX lancamentos_obra_data_idx ON public.lancamentos(obra_id,data DESC) WHERE deleted_at IS NULL; CREATE INDEX marcos_obra_data_idx ON public.marcos_avanco(obra_id,data);